export default {
  LOGIN_BG: require('../../../assets/image/LoginIcons/login_BG1.jpeg'),
  MOBILE_LOGO: require('../../../assets/image/BlueIcons/Mobile.png'),
  KEY_LOGO: require('../../../assets/image/Key.png'),
  //EYE_IMAGE: require('../../../assets/image/Account/eye.png'),
  //PROFILE_IMG: require('../../../assets/image/LoginIcons/profile.png'),
  HIDE: require('../../../assets/image/LoginIcons/hide.png'),
  UNHIDE: require('../../../assets/image/LoginIcons/unhide.png'),
  ORGANISATION: require('../../../assets/image/Organisation.png'),
  EMAIL: require('../../../assets/image/Email.png'),
  REGISTER_NAME: require('../../../assets/image/Account.png'),
  //WHITE_ARROW: require('../../../assets/image/LoginIcons/whiteArrow.png'),
  ACCOUNT_BG: require('../../../assets/image/Account/BG2.png'),
  IMAGE_ICON: require('../../../assets/image/Account/hide.png'),
  WHATS_UP: require('../../../assets/image/Account/Whatsapp.png'),
  SHARE: require('../../../assets/image/Account/Share.png'),
  VERSION: require('../../../assets/image/Account/Version.png'),
  RATE: require('../../../assets/image/Account/Rate.png'),
  MOVE_TO: require('../../../assets/image/BlueIcons/Moveto.png'),
  CUSTOM_ORDER: require('../../../assets/image/Account/Custom-Order.png'),
  ORDER_HISTORY: require('../../../assets/image/Account/Custom-Order.png'),
  EXCLUSIVE: require('../../../assets/image/Account/Exclusive.png'),
  LOGOUT: require('../../../assets/image/Account/Log-out.png'),
  GRAY_EMAIL: require('../../../assets/image/Account/Email.png'),
  PROFILE: require('../../../assets/image/Account/Account.png'),
  ABOUT: require('../../../assets/image/Account/About.png'),
  //SOCIAL_MEDIA: require('../../../assets/image/Account/profile.png'),
  FORWARD: require('../../../assets/image/Account/Forward2-.png'),
  VERIFY_BG: require('../../../assets/image/Account/BGGradient.png'),
  BACK_ICON: require('../../../assets/image/Account/back_button.png'),
  VERIFY_OTP_ICON: require('../../../assets/image/Account/Forward-Arrow.png'),
  CUSTOMORDER_BG: require('../../../assets/image/Account/CustomOrder_BG.png'),
  PLUS_ICON: require('../../../assets/image/Account/Plus_green.png'),
  EDIT: require('../../../assets/image/BlueIcons/Edit.png'),
  DELETE: require('../../../assets/image/BlueIcons/Delete.png'),
  CLOSE: require('../../../assets/image/close1.png'),

  GRAY_DOWN_ARROW: require('../../../assets/image/DownArrow.png'),
  BLUE_PLUS: require('../../../assets/image/BlueIcons/Plus.png'),
  BLUE_MINUS: require('../../../assets/image/BlueIcons/Minus.png'),
  BLUE_CART: require('../../../assets/image/BlueIcons/DarkCart.png'),
  BLUE_WISHLIST: require('../../../assets/image/BlueIcons/Heart.png'),

  BLUE_EMAIL: require('../../../assets/image/Profile/Email.png'),
  REMARK: require('../../../assets/image/BlueIcons/Remark.png'),
  SKY_LOGO: require('../../../assets/image/Account/skychainLogo.jpeg'),
  APP_LOGO: require('../../../assets/image/LoginIcons/SkyChainsLogo.png'),
};
